"""Add is_anonymous field to Reviews

Revision ID: 4b03e4964c74
Revises: 7a0f393ae434
Create Date: 2025-04-08 12:30:57.168346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b03e4964c74'
down_revision = '7a0f393ae434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
