"""Add 2FA fields to User model

Revision ID: 57b2fefcb6e3
Revises: 4b03e4964c74
Create Date: 2025-04-14 23:15:04.464541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b2fefcb6e3'
down_revision = '4b03e4964c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_enabled')

    # ### end Alembic commands ###
