name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Update apt and install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            curl \
            ca-certificates \
            libjpeg-dev \
            zlib1g-dev \
            libpng-dev

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | bash

      - name: Install deepseek
        run: |
          ollama run deepseek-r1:1.5b

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage

      - name: Run tests with coverage
        run: coverage run -m pytest tests/

      - name: Upload coverage results
        if: always()
        run: |
          coverage xml
          
      - name: Upload results to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Software-Engineering-Spring-2025/campus-job-review-system
